export enum AppRoutes {
  PRESENTATION_SCREEN = "PRESENTATION",
  LOGIN_SCREEN = "LOGIN",
  TERMS_SCREEN = "TERMS",
  HOME_SCREEN = "HOME",
  LEAGUES_SCREEN = "LEAGUES",
  SETTINGS_SCREEN = "SETTINGS",
}
